[tool.poetry]
name = "ygg-torrent-mcp"
version = "0.3.0"
description = "Ygg Torrent MCP Server"
authors = ["@philogicae"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/philogicae/ygg-torrent-mcp"
packages = [{ include = "ygg_torrent" }]


[tool.poetry.dependencies]
python = ">=3.10"
bencodepy = "*"
python-dotenv = "*"
rich = "*"
pydantic = "*"
requests = "*"
fastmcp = "*"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
