[project]
name = "codegrade"
version = "16.1.90"
description = "A client library for accessing CodeGrade"
authors = []
requires-python = ">=3.8.0,<4.0"
readme = "README.md"
license = "AGPL-3.0-only OR BSD-3-Clause-Clear"
dependencies = [
    "httpx>=0.19.0, <1.0.0",
    "structlog>=20.1.0,<21",
    "validate-email~=1.3",
    "python-dateutil>=2.8.1,<3",
    "typing-extensions>=4.13.2,<5",
]

[project.urls]
Documentation = "https://python.api.codegrade.com"

[dependency-groups]
dev = [
    "mypy>=1.3.0,<2",
    "sphinx>=6.2.1,<7",
    "sphinx-autodoc-typehints>=1.23.0,<2",
    "m2r2>=0.3.1,<0.4",
    "setuptools>=74.1.2,<75",
    "mistune<2.0.0",
    "furo>=2023.9.10,<2024",
    "docutils>=0.18.1,<0.19",
    "ruff>=0.11.10",
]

[tool.hatch.build.targets.sdist]
include = [
    "codegrade",
    "cg_maybe",
    "cg_dt_utils",
    "cg_request_args",
    "CHANGELOG.md",
    "py.typed",
]

[tool.hatch.build.targets.wheel]
include = [
    "codegrade",
    "cg_maybe",
    "cg_dt_utils",
    "cg_request_args",
    "CHANGELOG.md",
    "py.typed",
]

[tool.ruff]
line-length = 79

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"