[project]
name = "cyberstore"
version = "0.0.1b1"
description = "CyberStore: A high-performance, expression-aware data engine for financial time-series with Polars and ClickHouse."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clickhouse-df>=0.1.5",
    "connectorx>=0.4.3",
    "dynaconf>=3.2.11",
    "lark>=1.2.2",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "polars>=1.30.0",
    "sqlparse>=0.5.3",
    "xcals>=0.0.4",
    "ygo>=1.1.3",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["cyberstore", "cyberstore.*"]

[project.urls]
homepage = "https://github.com/link-yundi/cyberstore"
repository = "https://github.com/link-yundi/cyberstore"
