[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ducklake"
version = "0.1.0"
authors = [
  { name="Mark Raasveldt", email="mark.raasveldt@gmail.com" },
]
description = "DuckLake package for Python"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/duckdb/pyducklake"
Issues = "https://github.com/duckdb/pyducklake/issues"

