[tool.poetry]
name = "equipment-sequence"
version = "1.0.1"
description = "设备业务逻辑"
authors = ["LiuWei <183074632@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
passive-equipment = "1.22.2"


[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
