[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ffwrapy"
version = "1.0.2"
description = "A fast, flexible Python wrapper for FFmpeg, FFprobe, and FFplay — fetch metadata, encode, split, and run custom commands easily with real-time progress tracking."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "Apache License Version 2.0" }
authors = [
  { name = "भाग्य ज्योति (Bhagya Jyoti)" }
]
keywords = ["ffmpeg", "ffprobe", "ffplay", "media", "encoding", "mux", "remux", "wrapper", "python", "video", "audio", "subtitle", "vid", "aud", "sub", "split", "transcode"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Sound/Audio",
    "Development Status :: 5 - Production/Stable"
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/BhagyaJyoti22006/ffwrapy"
"Repository" = "https://github.com/BhagyaJyoti22006/ffwrapy"
"Issues" = "https://github.com/BhagyaJyoti22006/ffwrapy/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}
