[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MultiGATE"
version = "0.0.22"
description = "MultiGATE single cell"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = "==3.7.*"
license = { text = "MIT" }
authors = [
    { name = "Jinzhao LI", email = "jishuaimiao@gmail.com" },
    { name = "Jishuai MIAO", email = "jishuaimiao@gmail.com" }
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.7",
    "Operating System :: OS Independent"
]
dependencies = [
    "tensorflow-gpu==1.15.0",
    "scikit-learn>=1.0.2",
    "pandas>=1.3.5",
    "scanpy>=1.9.3",
    "jupyterlab>=3.6.7",
    "tqdm>=4.66.2",
    "matplotlib>=3.5.3",
    "networkx>=2.6",
    "pybedtools>=0.9.0",
    "seaborn>=0.12.2",
    "numpy>=1.21.6",
    "scipy>=1.7.3",
    "nvidia-ml-py3>=7.352.0", 
    "gseapy>=1.0.4",
    "rpy2>=3.5.16",
    "louvain>=0.8.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "twine>=4.0.2"
]

[tool.setuptools.packages.find]
include = ["MultiGATE", "MultiGATE.*"]
