[project]
name = "nsk"
version = "2.4.3"
description = "A Python library for NSK Automation"
authors = [
    {name = "Văn Ngoc Nhât Huy", email = "nhathuyd4hp@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "office365-rest-python-client>=2.6.2",
    "pandas>=2.2.3",
    "pre-commit>=4.2.0",
    "pydantic-settings>=2.9.1",
    "pyinstaller>=6.13.0",
    "pysharepoint>=0.1.7",
    "pywinauto>=0.6.9",
    "selenium>=4.32.0",
    "xlwings>=0.33.14",
]
license = { text = "MIT" }

[dependency-groups]
dev = [
    "openpyxl>=3.1.5",
    "pip>=25.1.1",
    "pyinstaller>=6.13.0",
    "pytest>=8.3.5",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["nsk*"]
exclude = ["tests*", "examples*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
