[project]
name = "mcp-jamie-test3"
version = "1.0.1"
description = "jamie test"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.2",
]

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-jamie-test3 = "mcp-jamie-test3:main"

[tool.hatch.build.targets.wheel]
packages = ["src/foo"]