[project]
name = "cacimbao"
version = "0.2.0"
description = "Base de dados brasileiras com dados reais para propÃ³sitos educacionais"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "narwhals>=0.7.0",
    "polars>=0.20.0",
    "requests>=2.31.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "cacimbao/",
]

[dependency-groups]
analysis = [
    "marimo>=0.13.9",
    "plotly==6.1.2",
]
dev = [
    "frictionless[parquet]>=5.18.1",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]
