[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autosec"
version = "1.0.20"
description = "A collection of utilities for security operations and automation."
authors = [
    {name = "Dylan Diamond", email = "dylandiamond1997@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "cryptography",
    "python-dotenv",
    "requests"

]

[project.urls]
"Homepage" = "https://github.com/dylandiamond97/Security-Automation-Utilities"

[project.scripts]
autocred = "autosec.cli:autocred_cli"
autolog = "autosec.cli:autolog_cli"

[tool.setuptools.packages.find]
include = ["autosec"]
exclude = ["gitignore", "Sample Uses"]