[project]
name = "PyUtils2024"
version = "0.0.9"
authors = [
  { name="Lixin", email="lixin1226@163.com" },
]
description = "tools"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
