[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ikml-doc"
version = "0.21.2"
authors = [
  { name="Chaitanya Lakkundi", email="chaitanya.lakkundi@gmail.com" },
  { name="Sai Susarla", email="sai.susarla@gmail.com" },
]
description = "A parser for IKML (Indic Knowledge Markup Language) Documents"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)",
]
dependencies = [
    "requests",
    "anytree",
]

[project.urls]
Homepage = "https://gitlab.com/siddhantakosha/public/software/ikml-pypi"
Issues = "https://gitlab.com/siddhantakosha/public/software/ikml-pypi/-/issues"
