[project]
name = "myfuntools"
version = "0.3.1"
dependencies = ["cffi","cryptography"] 


[build-system]
requires = ["setuptools", "wheel","cffi","cryptography"]
build-backend = "setuptools.build_meta"
