[project]
name = "juditha"
version = "0.1.1"
description = "A super-fast canonical name lookup service"
authors = [{ name = "Simon WÃ¶rpel", email = "simon.woerpel@pm.me" }]
license = "AGPLv3+"
readme = "README.md"
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11,<4"
dependencies = [
    "ftmq (>=0.8.5,<0.9.0)",
    "tantivy (>=0.24.0,<0.25.0)",
    "jellyfish (>=1.2.0,<2.0.0)",
]

[project.optional-dependencies]
api = ["fastapi (>=0.115.12,<0.116.0)"]

[project.scripts]
juditha = "juditha.cli:cli"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
isort = "^5.12.0"
flake8 = "^6.1.0"
pre-commit = "^3.4.0"
bump2version = "^1.0.1"
pytest = "^7.4.2"
pytest-coverage = "^0.0"
pytest-env = "^1.0.1"
httpx = ">=0.25.0"
mypy = "^1.5.1"
uvicorn = "^0.34.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest_env]
DEBUG = 1
JUDITHA_URI = "memory://"
