[project]
name = "scalar-django-ninja"
version = "0.1.1"
description = ""
authors = [
    {name = "Gpocas",email = "gpocas01@gmail.com"}
]
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Natural Language :: Portuguese (Brazilian)",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.12",
]


readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-ninja (>=1.4.3,<2.0.0)",
    "typing-extensions (>=4.14.0,<5.0.0)"
]

[project.urls]
repository = "https://github.com/Gpocas/scalar_django_ninja"
"Bug Tracker" = "https://github.com/Gpocas/scalar_django_ninja/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
