[project]
name = "fastapi-start-project"  # El nombre que se verÃ¡ en PyPI o pip
version = "0.0.4"
description = "Inicializador de proyectos FastAPI con entorno virtual, Docker y mÃ¡s"
authors = [{ name = "Edier", email = "edierguerra55@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
fastapi-start-app = "fastapi_init.cli:main"  # El comando que se ejecuta en terminal

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
