[project]

version = "0.0.13"
authors = [
    { name = "Xiaoqiang", email = "xiaoqiangclub@hotmail.com" },
]
dependencies = [
    "drissionpage (>=4.1.0.18,<5.0.0.0)",
    "pypiwin32 (>=223,<224) ; sys_platform == \"win32\"",
    "tqdm (>=4.67.1,<5.0.0)",
]
description = "基于 DrissionPage 封装的自用API，用于网页自动化。"
name = "AutoChrome"
readme = "README.md"
requires-python = ">=3.10"


[tool.poetry]
scripts.autochrome = "AutoChrome.utils.auto_chrome_cli:main"

[tool.poetry.group.dev.dependencies]
pypiwin32 = "^223"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

# 主源（清华镜像）
[[tool.poetry.source]]
name = "tuna"
priority = "primary" # 重要！必须显式声明为主源
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

# 次级源（官方 PyPI）
[[tool.poetry.source]]
name = "pypi"
priority = "supplemental" # 重要！必须显式声明为次级源
