[project]
name = "pcap-analyzer"
version = "0.1.5"
description = "A lightweight CLI tool for analyzing pcap files"
authors = [
    { name = "DaniÃ«l Schiffers", email = "daniel.schiffers@hva.nl" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "scapy>=2.6.1,<3.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest==8.3.5"
]

[project.scripts]
pcap-analyser = "analyser.__main__:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["analyser"]