[project]
name = "mcp-server-testing"
version = "0.2.0"
description = "A test server implementation for Model Context Protocol (MCP)"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{ name = "yareyaredesuyo", email = "yareyaredesuyo@gmail.com" }]
keywords = ["mcp", "llm", "model-context-protocol", "automation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["argparse>=1.4.0", "fastmcp>=2.5.2"]

[project.scripts]
mcp-server-testing = "mcp_server_testing:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
