# --- Configuration du système de build ---
[build-system]
requires = ["setuptools>=78.1.0"]
build-backend = "setuptools.build_meta"

# --- Métadonnées du projet ---
[project]
# Nom du package sur PyPI
name = "cinelytics_sdk"

# Numéro de version actuel (mettre à jour à chaque release)
version = "0.1.1"

# Auteur
authors = [
  { name = "KADER KOUADIO", email = "kkaderkouadio@gmail.com" }
]

# Brève description pour PyPI
description = "SDK Python léger et intuitif pour interagir avec l'API CINEMA_INSIGHTS, conçu pour les Data Analysts et Data Scientists"

# README utilisé pour la page PyPI
readme = "README.md"

# Type de licence (MIT)
license = { text = "MIT" }

# Version minimale de Python supportée
requires-python = ">=3.11"

# Classificateurs pour PyPI (affichés sur la page du package)
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
]

# --- Dépendances nécessaires à l’exécution ---
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.3",
    "backoff>=2.2.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1"
]

# --- Liens utiles (affichés sur PyPI) ---
[project.urls]
# ---Homepage = "https://pypi.org/project/cinelytics_sdk"
# ---Documentation = "https://cinema-insights.onrender.com/docs"


# --- Indique à setuptools d'utiliser src comme répertoire racine ---
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]