[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dphysicsengine"
version = "0.1.11"
description = "Motor físico para simulaciones"
authors = [
    {name = "David García Díaz", email = "davidgrcdiaz@gmail.com"}
]
requires-python = ">=3.7"
dependencies = ["pillow==9.1.1"]

[tool.setuptools.packages.find]
where = ["."]
