# build system is setuptools
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# project details
[project]
name = "threadtools"
version = "0.0.1"
authors = [{ name = "Drew Whitney", email = "Drew.Whitney@nrel.gov" }]
description = "Tools for synchronizing threads using better locks and signals."
readme = "README.md"
requires-python = ">=3.13"
# license
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]

# project links
[project.urls]
Homepage = "https://github.nrel.gov/dwhitney/threadtools"
Issues = "https://github.nrel.gov/dwhitney/threadtools/issues"

# setuptools
[tool.setuptools.packages.find]
where = ["src"]
include = ["threadtools"]

# pytest
[tool.pytest.ini_options]
minversion = "8.4"
addopts = "-q -s"
testpaths = ["./tests"]
python_files = ["*.py"]
python_functions = ["test_*"]
