[project]
name = "ximalaya"
version = "1.3.2"
description = "Python package for Ximalaya services."
requires-python = ">=3.10"
authors = [
    { name = "Garrett HE", email = "garrett.he@outlook.com" },
]
readme = "README.md"
keywords = [
    "ximalaya",
    "api",
    "service",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "jsonpath-ng>=1.7.0",
    "requests>=2.32.3",
    "pydantic>=2.11.5",
]

[project.license]
text = "BSD-3-Clause"

[project.urls]
homepage = "https://github.com/garrett-he/python-ximalaya"
repository = "https://github.com/garrett-he/python-ximalaya.git"
changelog = "https://github.com/garrett-he/python-ximalaya/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
    "chance>=0.110",
    "pre-commit>=4.2.0",
    "pylint>=3.3.6",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "tox>=4.23.2",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.scripts]
test = "pytest"
lint = "pylint src/ tests/"
