[project]
name = "pae-toolkit"
version = "0.0.6"
description = "PAE toolkit"
readme = "README.md"
authors = [{ name = "Yanguan02", email = "yanguan_02@126.com" }]
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.11.5",
    "typer>=0.16.0",
]

[project.scripts]
pae-toolkit = "pae_toolkit:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
