[tool.poetry]
name = "mrvbill"
version = "1.0.0"
description = "A command-line interface tool for managing bills and time tracking across different providers"
authors = ["Rares Modure <rares.modure@mrv-it.com>"]
readme = "README.md"
packages = [{include = "mrvbill", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.13"
click = ">=8.1.8,<9.0.0"
questionary = ">=2.1.0,<3.0.0"
requests = ">=2.32.3,<3.0.0"
pyfiglet = ">=1.0.2,<2.0.0"
rich = ">=13.9.4,<14.0.0"
weasyprint = ">=64.0,<65.0"
aiohttp = ">=3.9.3,<4.0.0"

[tool.poetry.scripts]
bill = "mrvbill:cli"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
