[build-system]
requires = ["build", "setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lcl_xhs_mcp"
version = "0.3.26"
authors = [
  { name="SoftEgLi", email="937423396@qq.com" },
]
description = "小红书mcp工具，支持自动登录，自动发布图文,headless第一版"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "html2image>=2.0.7",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.0",
    "openai>=1.79.0",
    "pillow>=11.2.1",
    "selenium>=4.32.0",
]

[project.urls]
Homepage = "https://github.com/SoftEgLi/xhs-mcp"
Issues = "https://github.com/SoftEgLi/xhs-mcp/issues"

[project.scripts]
xhs-server = "lcl_xhs_mcp.mcp_server:main"
